/**
 * German (Deutsch) Climate × Terrain Description Library
 *
 * 5 evocative read-aloud descriptions per climate × terrain combination.
 * Falls back to the English library when a combo has no German entry.
 */

import type { ClimateType } from './types';
import type { TerrainType } from './types';

type DescriptionKey = `${ClimateType}_${TerrainType}`;

export const CLIMATE_TERRAIN_DESCRIPTIONS_DE: Record<DescriptionKey, string[]> = {

  // ━━━ GEMÄSSIGT (TEMPERATE) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  temperate_plains: [
    'Sanft geschwungene grüne Felder erstrecken sich bis zum Horizont unter einem hohen blauen Himmel. Wildblumen tupfen das Grasland, und eine milde Brise trägt den Duft von Klee heran.',
    'Ein Flickenteppich aus Ackerland und wilden Wiesen breitet sich vor euch aus, durchzogen von einem mäandernden Bach. Vogelgesang erfüllt die warme Nachmittagsluft.',
    'Hohes Gras wogt wie ein smaragdenes Meer unter vereinzelten Wolken. Ein verwitterter Steinpfeiler — uralt und moosbedeckt — steht an einer Wegkreuzung.',
    'Die Ebene liegt still und weit. Bienenschwärme summen über Kräuterfelder, und in der Ferne dreht sich träge das Rad einer Windmühle.',
    'Der Wind streicht über goldgelbes Korn, das fast erntereif in der Sonne glänzt. Am Feldrand plätschert ein schmaler Graben zwischen Feldsteinen hindurch.',
  ],
  temperate_forest: [
    'Sonnenlicht fällt durch ein Dach aus Eichen und Buchen und sprenkelt den farnbedeckten Boden. Die Luft riecht nach feuchter Erde und Kiefernharz.',
    'Uralte Bäume ragen wie Kathedralensäulen empor; ihre verschränkten Äste lassen Schäfte goldenen Lichts hindurch. Ein Teppich aus Laub raschelt unter euren Füßen.',
    'Der Wald verdichtet sich um euch — efeubewachsene Stämme, summende Insekten und das ferne Klopfen eines Spechts. Ein Wildpfad windet sich zwischen den Wurzeln.',
    'Zwischen moosigen Stämmen hängen Nebelfetzen wie Schleier. Pilze sprießen aus morschem Holz, und irgendwo ruft ein Kuckuck.',
    'Ein klarer Bach schlängelt sich durch den Wald. Forellen blitzen unter der Oberfläche, und an den Ufern wachsen Vergissmeinnicht und Schaumkraut.',
  ],
  temperate_hills: [
    'Sanfte Hügel steigen und fallen wie erstarrte Wellen, ihre Hänge gesprenkelt mit Heidekraut und niedrigen Steinmauern. Schafe grasen auf einem fernen Kamm.',
    'Felsvorsprünge brechen durch grasige Hänge. Ein kühler Wind fegt über die Anhöhe und bietet weite Aussicht auf die Täler unten.',
    'Ihr erreicht einen Hügelkamm und erblickt ein grünes Tal, durchzogen von einem silbernen Bach. Alte Ruinen klammern sich an den gegenüberliegenden Hang, halb vom Efeu zurückerobert.',
    'Heidebewachsene Kuppen wechseln sich mit kleinen Senken ab, in denen sich Morgennebel hält. Ein Schäferpfad schlängelt sich zwischen Felsblöcken hindurch.',
    'Auf dem höchsten Punkt steht ein einzelner Findling, von Wind und Wetter geschliffen. Von hier reicht der Blick über ein Dutzend bewaldeter Hügel.',
  ],
  temperate_mountains: [
    'Graue Gipfel ragen über euch auf, durchzogen von Wasserfällen, die in neblige Schluchten stürzen. Der Pfad verengt sich zu einem in den Fels gehauenen Sims.',
    'Kiefernwälder weichen nacktem Stein, je höher ihr steigt. Die Luft wird dünn, und Adler kreisen vor einem wolkenverhangenen Himmel.',
    'Ein Gebirgspass öffnet sich zwischen zwei Gipfeln. Wind heult durch die Lücke und trägt Splitter aus Geröll und das ferne Donnergrollen eines Steinschlags.',
    'Schneefelder glänzen oberhalb der Baumgrenze. Ein schmaler Grat führt zwischen zwei Abgründen hindurch, und jeder Schritt muss wohlüberlegt sein.',
    'Aus einer Felswand sprudelt eine Quelle, die sich in Kaskaden den Hang hinab ergießt. Murmeltiere pfeifen warnend zwischen den Steinen.',
  ],
  temperate_swamp: [
    'Trübes Wasser erstreckt sich zwischen moosbehangenen Weiden. Der Boden matscht unter euren Füßen, und Binsen flüstern, während unsichtbare Wesen durch die Untiefen gleiten.',
    'Ein übelriechender Morast breitet sich vor euch aus, seine Oberfläche durchbrochen von fauligen Stämmen und Büscheln bleicher, schwammiger Pilze. Frösche quaken in einem endlosen Chor.',
    'Dichter Nebel klammert sich an dieses durchtränkte Tiefland. Die verdrehten Stämme toter Bäume recken sich gen Himmel wie greifende Finger.',
    'Irrlichter tanzen über der Wasseroberfläche — bläulich und unstetig. Der Geruch von Fäulnis und stehendem Wasser liegt schwer in der Luft.',
    'Zwischen Schilfinseln ragen verwitterte Holzpfähle empor — Überreste eines uralten Stegs. Reiher stehen reglos im flachen Wasser und warten auf Beute.',
  ],
  temperate_desert: [
    'Eine kahle Fläche aus trockener, rissiger Erde — vielleicht ein uralter Seeboden. Struppiger Ginster klammert sich zwischen gebleichten Steinen ans Leben.',
    'Vom Wind geschliffene Ödlande aus blassem Lehm erstrecken sich unter bedecktem Himmel. Vereinzelte Dornbüsche und ein gelegentlicher verkümmerter Baum sind die einzigen Lebenszeichen.',
    'Die Hitze flirrt über der ausgedörrten Ebene. Keine Wolke trübt den erbarmungslosen Himmel, und der Boden knirscht unter jedem Schritt.',
    'Ein ausgetrocknetes Flussbett schlängelt sich durch die staubige Einöde. Rissige Tonschollen knirschen wie Porzellan, und Eidechsen huschen über die Steine.',
    'Verstreute Knochen und ein umgestürzter Karren am Wegesrand erzählen von jenen, die dieses lebensfeindliche Land nicht rechtzeitig verlassen haben.',
  ],
  temperate_arctic: [
    'Ein später Frost überzieht den Boden mit Weiß. Die Luft beißt, und Eispfützen knacken unter euren Füßen, während ihr die gefrorene Wiese überquert.',
    'Das Hochplateau ist windgepeitscht und kahl, bestäubt mit Reif. Zähe Moose und Flechten sind die einzige Vegetation.',
    'Raureif glitzert auf jedem Grashalm. Die Stille ist beinahe greifbar — nur der Wind pfeift leise über die erstarrte Landschaft.',
    'Der Boden ist steinhart gefroren. Atemwolken steigen bei jedem Schritt auf, und ein blasser Mond steht noch am Morgenhimmel.',
    'Ein gefrorener Tümpel spiegelt den grauen Himmel. Am Rand kauern kümmerliche Sträucher, ihre Zweige von Eiskristallen schwer.',
  ],
  temperate_coastal: [
    'Weiße Kreidefelsen überblicken einen Kiesstrand, an dem sanft die Wellen lecken. Seevögel kreisen über euch und rufen in eine steife Salzbrise.',
    'Eine geschützte Bucht mit goldenem Sand und Gezeitenpools voller Anemonen. Die Ruinen eines Fischerdorfs stehen oberhalb der Flutlinie.',
    'Die Küste ist ein Gewirr aus grasigen Dünen und Wattflächen, belebt vom Schrei der Möwen und dem rhythmischen Tosen der Brandung.',
    'Muschelschalen knirschen unter euren Stiefeln, während der Wind das Seegras zu Wellen bläst. Am Horizont schimmert ein Leuchtturm im Dunst.',
    'Felsige Klippen fallen steil ins Meer ab. In den Nischen nisten Kormorane, und der Geruch von Tang und Salz liegt schwer in der Luft.',
  ],
  temperate_jungle: [
    'Ein ungewöhnlich dichter und schwüler Abschnitt eines Laubwaldes, fast tropisch in seiner Üppigkeit. Ranken bedecken jede Fläche, und die Luft summt vor Insekten.',
    'Dieses geschützte Tal fängt Wärme und Feuchtigkeit ein und bringt ein unwahrscheinliches Gewirr von Grün hervor, das eher in südliche Länder passt.',
    'Die Luftfeuchtigkeit ist drückend. Moos und Farne bedecken jeden Stein, und bunte Schmetterlinge flattern zwischen riesigen Blättern.',
    'Üppige Vegetation überwuchert verfallene Mauerreste. Selbst die Luft scheint grün gefärbt vom diffusen Licht, das durch das dichte Blätterdach fällt.',
    'Ein Bachlauf verschwindet unter einem Dach aus Farnen und Schlingpflanzen. Irgendwo ruft ein fremdartiger Vogel — schrill und durchdringend.',
  ],
  temperate_underdark: [
    'Ein klaffendes Erdloch öffnet sich in der Wiese, seine Ränder von Farnen gesäumt. Darunter gähnt Dunkelheit — und mit ihr ein kalter, mineralischer Luftzug.',
    'Die Höhlen am Hang sind örtlich bekannt. Stalaktiten tropfen auf einen abgetretenen Pfad, der in lampenbeleuchtetes Dämmerlicht hinabführt.',
    'In der Tiefe glitzern feuchte Wände im Schein eurer Fackeln. Das Echo eurer Schritte hallt endlos weiter — der Gang scheint kein Ende zu nehmen.',
    'Aus dem Felsvorsprung strömt ein kühler Luftzug, der nach Erde und Stein riecht. Spinnweben so groß wie Wagenräder hängen am Eingang.',
    'Der Höhleneingang ist kaum mehr als ein Spalt im Fels, doch dahinter weitet sich eine Halle mit tropfsteingespickter Decke.',
  ],
  temperate_water: [
    'Ein breiter, langsam fließender Strom spiegelt die grünen Hügel beider Ufer. Fische kräuseln die Oberfläche, und Reiher stehen reglos am Wasser.',
    'Ein tiefer See von überraschend klarem Blau füllt eine natürliche Mulde zwischen bewaldeten Hügeln. Ein bröckelnder Steinanleger ragt vom Ufer ins Wasser.',
    'Seerosen bedecken die stille Oberfläche eines Weihers. Libellen schießen hin und her, und am Ufer flüstert Schilf im Wind.',
    'Das Wasser ist so klar, dass ihr die Kiesel auf dem Grund zählen könntet. Ein hölzerner Steg, von der Zeit gebeugt, ragt über die Flachwasserzone.',
    'Nebel steigt vom See auf und verschmilzt mit dem blassen Morgenlicht. Ein einsames Fischerboot treibt ohne Insassen auf dem spiegelglatten Wasser.',
  ],
  temperate_road: [
    'Eine gut gepflegte Kopfsteinstraße durchschneidet die Landschaft, flankiert von niedrigen Steinmauern und gelegentlich beschattet von uralten Ulmen.',
    'Die Handelsstraße ist breit und von Wagenrädern zerfurcht. Ein Meilenstein gibt die Entfernung zur nächsten Stadt an. Reisende bevölkern die Strecke in beide Richtungen.',
    'Am Straßenrand steht ein hölzernes Wegkreuz mit verblasster Inschrift. Wildblumen wachsen zwischen den Pflastersteinen, wo der Verkehr sie verschont hat.',
    'Ein Gasthof mit rauchendem Schornstein steht an einer Wegkreuzung. Das Schild knarrt im Wind — „Zum Goldenen Hirsch".',
    'Die Straße führt durch eine Allee alter Linden. Ihre Blüten duften süß, und Bienen summen träge im Schatten der Kronen.',
  ],

  // ━━━ ARKTISCH (ARCTIC) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  arctic_plains: [
    'Eine endlose Fläche gefrorener Tundra erstreckt sich unter einem bleigrauen Himmel. Der Wind peitscht Eiskristalle ins Gesicht und schneidet durch jede Kleidungsschicht.',
    'Der Permafrost knirscht unter euren Stiefeln. Niedrige, zähe Sträucher sind das einzige Lebenszeichen auf dieser gesichtslosen weißen Ebene — abgesehen vom fernen Heulen der Wölfe.',
    'Ein weites Schneefeld liegt gespenstisch still da; nur das Knarzen des Eises durchbricht die Stille. Nordlicht schimmert blass am Horizont, selbst am Tag.',
    'Die Kälte ist erbarmungslos. Jeder Atemzug schmerzt in der Lunge, und die Wimpern verkleben von Frost. Nichts bewegt sich in dieser weißen Leere.',
    'Schneeverwehungen haben die Landschaft in sanfte Wellen geformt. Ein einzelner Polarfuchs schleicht in der Ferne, sein weißes Fell kaum vom Schnee zu unterscheiden.',
  ],
  arctic_forest: [
    'Frostüberzogene Kiefern stehen wie geisterhafte Wachen, ihre Äste unter der Last des Schnees gebogen. Euer Atem hängt in der stillen, bitter kalten Luft.',
    'Die Taiga ist dicht und dunkel, der Boden ein gefrorener Teppich aus Nadeln und Eis. Irgendwo vor euch knackt ein Ast unter dem Gewicht unsichtbarer Tiere.',
    'Blasse Birken ragen aus tiefem Schnee, ihre Rinde blättert wie Pergament. Eiszapfen hängen an jedem Ast und glitzern in der schwachen Wintersonne.',
    'Verschneite Fichten stehen dicht an dicht wie ein Heer stummer Soldaten. Die Stille ist so tief, dass ihr das Fallen einzelner Schneeflocken hören könnt.',
    'Ein Elch steht reglos zwischen den Bäumen und beobachtet euch mit dunklen Augen. Sein Atem dampft in der eisigen Luft, bevor er lautlos im Unterholz verschwindet.',
  ],
  arctic_hills: [
    'Windgeschliffene Hügel aus nacktem Fels und Permafrost erheben sich aus der gefrorenen Ebene. Schnee sammelt sich in jeder Spalte, und die exponierten Grate sind glatt wie poliertes Eis.',
    'Niedrige, abgerundete Hügel unter tiefem Schnee erstrecken sich in alle Richtungen. Die einzigen Merkmale sind gelegentliche Findlinge, von urzeitlichen Gletschern abgelagert.',
    'Der Wind faucht über die kahlen Kuppen und formt den Schnee zu bizarren Skulpturen. In einer geschützten Senke dampft ein winziges Thermalbecken.',
    'Verstreute Felsbrocken ragen aus dem Schnee wie die Knochen eines vergessenen Riesen. Zwischen den Hügeln heult der Wind mit einer Stimme, die fast menschlich klingt.',
    'Die Hügelkuppen sind blank und eisig; kein Halt für den Fuß. Unten im Tal schlängelt sich ein halb zugefrorener Bach zwischen Schneewehen hindurch.',
  ],
  arctic_mountains: [
    'Aufragende Gipfel aus Eis und schwarzem Stein durchstoßen den grauen Himmel. Gletscher ächzen in den Tälern, ihre Oberflächen von tiefen blauen Spalten zerrissen.',
    'Der Berg ist eine Festung aus Eis. Wind peitscht die exponierte Flanke, und Lawinenrinnen zeichnen Schneisen der Verwüstung in die Hänge.',
    'Ein gefrorener Wasserfall ergießt sich die Felswand hinab, in der Bewegung erstarrt — Tonnen blauweißen Eises, unheimlich schön und völlig unpassierbar.',
    'Schnee und Eis bedecken alles. Nur schwarze Felsnadeln durchbrechen die weiße Fläche wie die Zinnen einer Winterburg.',
    'Der Aufstieg ist lebensgefährlich. Jeder Handgriff muss sitzen, denn unter dem Schnee lauert blankes Eis. Ein Fehltritt, und die Schlucht unter euch wartet geduldig.',
  ],
  arctic_swamp: [
    'Dieses Tiefland ist ein Labyrinth aus gefrorenen Tümpeln und frostgehobenen Hügeln. In wärmeren Monaten wäre es ein Moor; jetzt ist es ein tückisches Gewirr aus dünnem Eis.',
    'Das Marschland ist zu einem Durcheinander aus Eis und toten Binsen gefroren. Dunkles Wasser bewegt sich unter der Oberfläche, und das Eis stöhnt bedrohlich.',
    'Das Eis gibt bei jedem Schritt ein unheimliches Knarzen von sich. Blasen steigen aus der Tiefe auf und bleiben unter der Oberfläche gefangen wie kleine Gefängnisse.',
    'Abgestorbene Schilfhalme ragen aus dem Eis wie braune Speere. Der Geruch von Schwefel und fauligem Wasser hängt noch in der Kälte.',
    'Hier und da ist das Eis nachgegeben. Schwarze Löcher gähnen auf, aus denen ein modrig-feuchter Hauch aufsteigt.',
  ],
  arctic_desert: [
    'Eine polare Wüste aus windgepresstem Schnee und freiliegendem Schotter. Kein Niederschlag fällt hier — nur eine endlose, knochentrockene Kälte, die Lippen aufspringen und Haut reißen lässt.',
    'Die Eisdecke erstreckt sich bis zum Horizont, merkmallos und blendend weiß. Die Stille ist absolut, nur gebrochen von eurem eigenen schweren Atmen.',
    'Weder Schnee noch Regen fallen auf diese eintönige Fläche. Es ist zu kalt selbst für Wolken. Nur der Wind und ihr seid hier lebendig.',
    'Die Luft ist so trocken, dass jeder Atemzug in der Kehle brennt. Das Licht blendet von allen Seiten — reflektiert vom endlosen Eis.',
    'Nichts. Nur Weiß. Die Welt scheint ihren Rand erreicht zu haben, und dahinter liegt nur noch Leere.',
  ],
  arctic_arctic: [
    'Der tiefste Winter hält das Land in eisernem Griff. Die Temperaturen sind tödlich; bloße Haut erfriert in Minuten. Der Himmel bietet nur ein schmales Band grauer Dämmerung.',
    'Dies ist die tiefe Tundra — wo selbst die widerstandsfähigsten Wesen sich unter die Erde zurückziehen. Die Welt ist Weiß auf Weiß, richtungslos und erbarmungslos.',
    'Die Sonne schafft es nicht mehr über den Horizont. Ein ewiges Zwielicht liegt über dem Land, und selbst die Sterne scheinen vor Kälte zu zittern.',
    'Eis so dick, dass es beim Gehen unter euch klingt wie eine dumpfe Glocke. Hier gibt es kein Entkommen — nur Ausdauer oder Untergang.',
    'Selbst die Luft scheint zu gefrieren. Kristalle tanzen im schwachen Licht und legen sich wie Diamantenstaub auf eure Kleidung.',
  ],
  arctic_coastal: [
    'Eisverstopftes Wasser klatscht gegen ein gefrorenes Ufer. Meereis erstreckt sich weit hinaus in den grauen Ozean, durchbrochen von den dunklen Umrissen der Eisberge.',
    'Das Küstenland ist ein Durcheinander aus gefrorener Gischt und schwarzem Vulkangestein. Robbenkolonien bellen von Eisschollen, und die Luft stinkt nach Salzwasser und Kälte.',
    'Mächtige Eisschollen schieben sich krachend übereinander, wo die Gezeiten arbeiten. Der Horizont verschwimmt — Meer und Himmel sind gleichermaßen grau.',
    'Gefrorene Wellenkämme säumen die Küste wie eine Skulpturenallee. In der Ferne bricht ein Eisberg mit donnerndem Getöse.',
    'Der Strand ist eine Fläche aus gefrorenem Kies und Treibholz, überzogen mit einer Schicht aus Salzkristallen und Eis.',
  ],
  arctic_jungle: [
    'Wider jede Vernunft hat sich dichte Vegetation um eine geothermale Öffnung angesiedelt. Dampf steigt in die eisige Luft, und Farne wachsen mitten im Schnee.',
    'Ein geschütztes Heißquellentaltal nährt eine unmögliche Insel aus Grün. Der Kontrast zwischen der gefrorenen Einöde und diesem üppigen Mikrodschungel ist verstörend.',
    'Dampf wabert zwischen tropisch anmutenden Pflanzen, während ringsum Schnee liegt. Es fühlt sich an, als hättet ihr eine andere Welt betreten.',
    'Riesige Farne und moosbedeckte Steine umgeben ein dampfendes Becken. Schmetterlinge — hier, in der Arktis! — flattern zwischen den Blättern.',
    'Die Wärme der heißen Quellen hat einen Kokon des Lebens geschaffen. Doch tretet ihr einen Schritt zu weit, empfängt euch die beißende Kälte der Tundra.',
  ],
  arctic_underdark: [
    'Ein Riss im Gletscher führt hinab in die Dunkelheit. Eiswände weichen Stein, und die Temperatur steigt tatsächlich, je tiefer ihr absteigt — beunruhigend.',
    'Der Höhlenmund haucht eine Wolke warmen Nebels in die eisige Luft. Drinnen leuchten Flechten schwach an feuchten, glitschigen Wänden.',
    'Das Eis endet abrupt, und nackter Fels übernimmt. Ein unterirdischer Strom gurgelt in der Tiefe, überraschend warm an den Fingern.',
    'Eiszapfen so lang wie Schwerter säumen den Eingang. Dahinter öffnet sich eine Grotte, in der phosphoreszierende Pilze ein unwirkliches Licht verbreiten.',
    'Der Abstieg ist steil, aber mit jedem Meter wird es wärmer. Irgendwo tief unten pulsiert ein orangerotes Glühen — vulkanische Aktivität unter dem Eis.',
  ],
  arctic_water: [
    'Ein gefrorener See erstreckt sich vor euch, seine Oberfläche vom Wind blank gefegt. Dunkle Silhouetten bewegen sich unter dem dicken Eis — Fische oder vielleicht etwas Größeres.',
    'Der Fluss ist fest gefroren und bildet eine natürliche Eisstraße. Druckrücken beulen die Oberfläche dort, wo Strömungen darunter arbeiten.',
    'Das Eis funkelt im schwachen Licht wie ein riesiger Spiegel. Unter der Oberfläche schimmert es grün und blau — Luftblasen, eingeschlossen in der Tiefe.',
    'Am Rand des zugefrorenen Sees ragen Schilfstoppeln durch den Schnee. Spuren im Eis verraten, dass hier vor Kurzem etwas Schweres entlanggegangen ist.',
    'Ein zugefrorener Wasserfall hängt an der Felswand — eine Skulptur aus Eis und eingefangener Bewegung.',
  ],
  arctic_road: [
    'Der Weg ist kaum sichtbar — nur eine Reihe von Pflöcken im Schnee, jeder gekrönt von einer ausgefransten roten Flagge. Der Wind versucht, euch vom Pfad zu stoßen.',
    'Eine gefrorene Handelsroute, festgestampft von Schlittenkufen. Reifrüberzogene Meilensteine zeigen Entfernungen in zwergischen Runen an.',
    'Unter dem Schnee erspürt ihr unebene Pflastersteine — der alte Weg existiert noch, doch er ist fast vollständig begraben.',
    'Alle paar hundert Schritt steht ein steinerner Wegweiser, halb im Schnee versunken. Die Richtungsangaben sind kaum noch zu entziffern.',
    'Schlittenspuren und Hufabdrücke sind die einzigen Hinweise, dass andere vor euch hier waren. Der Wind füllt sie binnen Minuten mit frischem Schnee.',
  ],

  // ━━━ TROPISCH (TROPICAL) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  tropical_plains: [
    'Eine sonnenverbrannte Savanne erstreckt sich unter einem immensen Himmel. Hohes goldenes Gras wiegt sich, und Akazienbäume werfen spindeldürre Schatten. Entfernte Herden wirbeln eine Staubwolke auf.',
    'Das schwüle Grasland summt vor Insektenleben. Termitenhügel erheben sich wie irdene Türme, und die Luft flirrt vor Hitze.',
    'Die Hitze steht wie eine Wand. Geier kreisen träge über der Steppe, und am Horizont schimmern Trugbilder von Wasserflächen, die es nicht gibt.',
    'Eine Herde Gnus zieht in der Ferne vorbei. Das Donnern ihrer Hufe ist selbst über die weite Ebene zu hören.',
    'Zwischen den Gräsern raschelt es — eine Schlange oder ein kleines Raubtier. Die Savanne ist trügerisch friedlich; unter der Oberfläche lauert Gefahr.',
  ],
  tropical_forest: [
    'Der Dschungel rückt heran — eine Mauer aus Grün auf allen Seiten. Papageien kreischen über euch, Lianen hängen wie Vorhänge, und die Luft ist dick genug zum Trinken.',
    'Gewaltige Bäume mit Brettwurzeln überragen eine dichte Unterschicht aus Farnen und Palmen. Lichtschäfte beleuchten Wolken aus Pollen und Schmetterlingen.',
    'Das Kronendach ist so dicht, dass es ein ewiges smaragdenes Dämmerlicht darunter schafft. Wasser tropft unablässig; alles ist feucht und lebendig.',
    'Orchideen und Bromelien bedecken jeden Ast. Die Vielfalt der Geräusche ist überwältigend — Vogelrufe, Insektensummen, das Rascheln unsichtbarer Tiere.',
    'Ein umgestürzter Baumriese liegt quer über den Pfad. Auf seinem morschen Stamm wächst bereits ein ganzer Garten aus Pilzen, Moosen und Keimlingen.',
  ],
  tropical_hills: [
    'Üppig grüne Hügel steigen steil an, ihre Hänge von uralten Händen terrassiert oder durch Monsunregen zerfurcht. Wasserfälle stürzen durch jede Schlucht.',
    'Der Hang ist in dichte tropische Vegetation gekleidet, durchbrochen von Aufschlüssen roten Lateritgesteins. Wolken klammern sich an den Gipfel.',
    'Reisterrassen leuchten in verschiedenen Grüntönen den Hang hinab. Bauern in kegelförmigen Hüten arbeiten knöcheltief im Wasser.',
    'Von der Hügelkuppe habt ihr einen atemberaubenden Blick auf den endlosen Dschungel unter euch — ein Meer aus Grün, aus dem Nebel aufsteigt.',
    'Ein Wasserfall stürzt über eine Felslippe in ein natürliches Becken. Das Wasser ist klar und einladend, doch Krokodilspuren säumen das Ufer.',
  ],
  tropical_mountains: [
    'Nebelwälder hüllen den Berghang ein, ihre Bäume geschmückt mit Epiphyten und Orchideen. Nebel rollt in großen weißen Vorhängen durch die Pässe.',
    'Der Vulkangipfel dampft leise, seine Hänge grün bis zur Baumgrenze und darüber nackter schwarzer Fels. Die Luft ist selbst in der Höhe warm.',
    'Kolibris schießen durch die Nebelschleier, die den Bergwald durchziehen. Tropfen perlen von Riesenfarnen, die so groß sind wie Schirme.',
    'Der Pfad windet sich durch moosbedeckte Felsen empor. In der Ferne grummelt der Vulkan — eine Erinnerung an die Kräfte, die diese Berge erschufen.',
    'Über der Baumgrenze öffnet sich eine karge Mondlandschaft aus erkalteter Lava. Dampf zischt aus Spalten, und der Schwefelgeruch wird stärker.',
  ],
  tropical_swamp: [
    'Ein Mangrovensumpf erstreckt sich bis zum Horizont — verknotete Wurzeln, brackiges Wasser und das Dröhnen einer Million Mücken. Krokodilaugen tauchen auf und verschwinden.',
    'Das tropische Feuchtgebiet ist ein Fest des Lebens: Reiher, Schlangen, Fische, die aus dunklem Wasser springen. Die Hitze ist erstickend und der Geruch überwältigend.',
    'Glühwürmchen tanzen über dem dunklen Wasser, als hielten die Sterne einen Maskenball. Doch das leise Plätschern verrät, dass etwas Großes in der Nähe lauert.',
    'Mangroven strecken ihre knorrigen Wurzeln in alle Richtungen. Jeder Schritt muss sorgfältig gewählt werden — ein Fehltritt, und ihr versinkt bis zur Hüfte.',
    'Ein erstickender Hauch aus Verwesung und Blütenduft hängt in der Luft. Bunte Frösche sitzen auf breiten Blättern und beobachten euch mit goldenen Augen.',
  ],
  tropical_desert: [
    'Ein sonnenverbrannter Streifen Hartboden zwischen Dschungelregionen. Dorniges Gebüsch und Kakteen klammern sich an die rissige rote Erde. Hitzeflimmern tanzt am Horizont.',
    'Diese trockene Tasche im Dschungelgürtel bäckt unter erbarmungsloser Sonne. Eidechsen huschen zwischen den Felsen, und Geier kreisen geduldig.',
    'Der Übergang vom Dschungel zur Dürre ist erschreckend abrupt. Innerhalb weniger Schritte weicht üppiges Grün kargem, rissigem Boden.',
    'Einzelne verdorrte Büsche stehen wie Mahnmale in der Hitze. Ihr Schatten reicht kaum, um eine Maus zu bedecken.',
    'Der Boden strahlt Hitze ab wie ein Ofen. Selbst die Insekten haben sich zurückgezogen, und nur das Knistern der ausgedörrten Erde ist zu hören.',
  ],
  tropical_arctic: [
    'Eine unmögliche Anomalie — Frost und Eis bestehen mitten in tropischer Hitze. Irgendeine Kältemagie muss diese widernatürliche Frostzone aufrechterhalten.',
    'Die Temperatur fällt scharf ab, als ihr diese magisch gekühlte Region betretet. Reif überzieht die Ränder tropischer Blätter und erzeugt einen unheimlichen Kontrast.',
    'Eisblumen sprießen an den Stämmen von Palmen. Die Luft schmeckt nach Magie und Frost — ein Ort, der nicht sein sollte und doch existiert.',
    'Ein Ring aus Eis umgibt eine Ruine im Dschungel. Was auch immer diesen Fluch gewirkt hat, seine Macht ist noch nicht versiegt.',
    'Tropische Vögel sitzen reglos auf vereisten Ästen, als wären sie mitten im Flug eingefroren. Es ist ein Bild von verstörender Schönheit.',
  ],
  tropical_coastal: [
    'Weiße Sandstrände, gesäumt von wiegenden Palmen. Türkise Wellen lecken ans Ufer, und farbenfrohe Fische huschen durch die kristallklaren Untiefen.',
    'Ein dampfiger Küstenstreifen, wo Dschungel auf Meer trifft. Mangrovenwurzeln reichen in Gezeitenpools, und Einsiedlerkrebse huschen über den nassen Sand.',
    'Das Riff schimmert durch das flache Wasser in allen Farben. Korallen, Seesterne und Seeigel verwandeln den Meeresboden in ein lebendiges Mosaik.',
    'Eine Lagune von unwirklichem Blau liegt geschützt zwischen Felsvorsprüngen. Pelikane stürzen sich kopfüber ins Wasser und tauchen mit vollen Schnäbeln wieder auf.',
    'Der Sand ist so fein und weiß, dass er unter der Sonne fast blendet. Kokospalmen spenden den einzigen Schatten, und das Rauschen der Wellen wirkt hypnotisch.',
  ],
  tropical_jungle: [
    'Dies ist tiefer Dschungel — unberührt, urzeitlich. Das Kronendach ragt sechzig Meter über euch auf. Ihr seid Eindringlinge in einer Welt, die jemand anderem gehört.',
    'Jede Fläche lebt: Flechten, Moos, kriechende Insekten, Blüten in unmöglichen Farben. Die Luft vibriert von einem ständigen Chor aus Vögeln, Fröschen und namenlosen Wesen.',
    'Dinosaurierspuren versinken im schlammigen Pfad. Der Dschungel hier ist uralt über jedes Begreifen, und er beobachtet euren Durchzug mit tausend unsichtbaren Augen.',
    'Lianen so dick wie Arme hängen von den Baumriesen herab. Irgendwo in der Ferne grollt ein Donner — oder ist es das Brüllen eines Raubtiers?',
    'Ein Strom von Blattschneiderameisen kreuzt euren Pfad wie eine lebende Straße. Die Luft ist so feucht, dass eure Kleidung binnen Minuten durchnässt ist.',
  ],
  tropical_underdark: [
    'Ein Cenote — ein gewaltiges Erdloch — öffnet sich im Dschungelboden, seine senkrechten Wände triefend von Wurzeln und Ranken. Türkises Wasser schimmert weit unten.',
    'Der Höhleneingang verbirgt sich hinter einem Wasserfall. Drinnen malen biolumineszente Pilze die Wände in gespenstisches Blaugrün.',
    'Stalaktiten tropfen in ein unterirdisches Becken von überirdischer Klarheit. Fische ohne Augen gleiten lautlos durch das stille Wasser.',
    'Wurzeln bahnen sich ihren Weg durch die Höhlendecke und hängen wie natürliche Seile herab. In ihrem Geflecht nisten Fledermäuse zu Hunderten.',
    'Die Luft unter der Erde ist kühl und feucht — eine willkommene Erleichterung nach der Dschungelhitze. Doch die Dunkelheit birgt ihre eigenen Gefahren.',
  ],
  tropical_water: [
    'Ein breiter, schlammiger Fluss windet sich durch den Dschungel, seine Oberfläche gepunktet mit Seerosenblättern und dem gelegentlichen Baumstamm, der vielleicht keiner ist.',
    'Ein dampfender Dschungelsee, dessen Wasser spiegelglatt und dunkel liegt. Fremdartige Vögel rufen vom fernen Ufer, und Blasen steigen aus der Tiefe.',
    'Das Flusswasser ist braun und träge. Kaimane dösen am Ufer, und farbenfrohe Eisvögel schießen über die Oberfläche.',
    'Ein Wasserfall speist einen natürlichen Pool, umgeben von Riesenfarnen. Das Wasser dampft leicht — gespeist von heißen Quellen tief im Fels.',
    'Piranhas? Vielleicht. Das Wasser verrät nichts. Aber die Einheimischen meiden diese Stelle — und das sollte euch zu denken geben.',
  ],
  tropical_road: [
    'Ein überwucherter Pfad, in den Dschungel geschlagen — bereits erobert die Vegetation ihn zurück. Machetenhiebe zeichnen die Baumstämme.',
    'Ein erhöhter Holzsteg überspannt das Feuchtgebiet, seine Planken grün vor Algen und von der Feuchtigkeit verzogen.',
    'Der Weg ist kaum mehr als eine Spur zwischen den Bäumen. Ameisen, Käfer und Tausendfüßler bevölkern den Boden, als gehöre er ihnen — weil er das auch tut.',
    'Verfallene Steinplatten deuten auf eine alte Straße hin, doch der Dschungel hat sie fast vollständig verschlungen. Ranken und Wurzeln sprengen den Belag.',
    'Der Pfad folgt dem Flussufer — manchmal fest, manchmal knöcheltief im Schlamm. Moskitos umschwirren euch in dichten Wolken.',
  ],

  // ━━━ ARID (TROCKEN) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  arid_plains: [
    'Eine sonnenversengte Fläche aus hartgepackter Erde und spärlichem, verdorrtem Gras. Die Hitze verzerrt die Luft zu flimmernden Trugbildern am Horizont.',
    'Die Steppe ist trocken und staubig, übersät mit Dornbüschen und den gebleichten Knochen von Tieren. Ein heißer Wind weht aus dem Süden.',
    'Risse durchziehen den ausgedörrten Boden wie ein Netz. Nicht einmal Insekten scheinen sich hier wohlzufühlen — nur die Stille und der Wind.',
    'Staubteufel wirbeln über die Ebene und zeichnen spiralförmige Muster in den Sand. Am Horizont zittert die Luft vor Hitze.',
    'Eine vertrocknete Schlangenhaut liegt am Wegesrand — das einzige Zeichen, dass hier etwas lebt. Oder gelebt hat.',
  ],
  arid_forest: [
    'Verdrehte, dürreresistente Bäume klammern sich an den trockenen Boden — ihre Stämme knorrig, ihre Blätter graugrün und wachsig. Jeder Schatten ist ein kostbares Refugium.',
    'Ein lichter Wald aus Straucheiche und Wacholder besetzt dieses trockene Plateau. Der Boden ist sandig, und das Laub raschelt wie Papier.',
    'Die Bäume stehen weit auseinander, als misstrauten sie einander. Ihre Wurzeln graben sich tief in den Boden auf der Suche nach dem letzten Tropfen Wasser.',
    'Harz tropft aus den rissigen Stämmen und verströmt einen herben, würzigen Duft. Eidechsen sonnen sich auf den Steinen zwischen den Bäumen.',
    'Ein einsamer Skorpion krabbelt über einen Ast. Der Wald ist still — zu still. Selbst die Vögel haben sich in den Schatten zurückgezogen.',
  ],
  arid_hills: [
    'Kahle Mesas aus rotem Fels und gewundene Canyons, geschnitten von einem uralten Fluss. Der Stein ist in Bändern von Rost, Bernstein und Creme geschichtet.',
    'Vom Wind geformte Sandsteinhügel erheben sich vom Wüstenboden, von Äonen in seltsame, organische Formen gemeißelt.',
    'Felsbogen und Steinsäulen stehen wie die Ruinen einer vergessenen Zivilisation. Die untergehende Sonne taucht alles in glühendes Orange.',
    'In den Schatten der Canyonwände ist es überraschend kühl. Felszeichnungen uralter Völker schmücken die glatten Wände.',
    'Die Hügel sind karg und lebensfeindlich, doch in einer versteckten Spalte wächst ein einzelner, trotziger Kaktus mit einer leuchtend roten Blüte.',
  ],
  arid_mountains: [
    'Aufragende Sandsteinklippen glühen rotgolden im harten Licht. Kein Tropfen Wasser ist irgendwo sichtbar — nur endlose, bröckelnde Felswände.',
    'Der Berg ist eine sonnengebleichte Festung. Wüstenwinde haben Bögen und Pfeiler aus dem weicheren Gestein geschnitzt und eine fremdartige Landschaft erschaffen.',
    'Der Aufstieg ist mörderisch in der Hitze. Jeder Schluck Wasser muss eingeteilt werden, und die Sonne brennt erbarmungslos auf euren Nacken.',
    'In einer Felsnische entdeckt ihr ein verlassenes Einsiedlernest — Tonkrüge, eine Feuerstelle und Knochenreste. Wer auch immer hier lebte, ist lange fort.',
    'Der Gipfel bietet einen atemberaubenden Blick auf die Wüste — endloses Gold und Rot, soweit das Auge reicht.',
  ],
  arid_swamp: [
    'Eine Alkaliebene — blendend weißer Salzkrusten über flachen, salzigen Tümpeln. Das Wasser ist untrinkbar, und der Gestank von Mineralablagerungen sticht in der Nase.',
    'Eine schlammige Oase, umgeben von rissiger Erde — ein sterbendes Feuchtgebiet, gespeist von einer versiegenden unterirdischen Quelle.',
    'Das Salz knirscht unter euren Stiefeln wie frischer Schnee. Aber die Hitze hier hat nichts Winterliches an sich.',
    'Salzpfannen spiegeln den Himmel so perfekt, dass ihr nicht wisst, wo oben und unten ist. Ein Trugbild, das jeden Kompass nutzlos macht.',
    'Zerbrochene Tonschalen und verrostete Eimer liegen verstreut — Überreste jener, die versuchten, diesem Ödland Wasser abzuringen.',
  ],
  arid_desert: [
    'Dünen aus feinem, goldenem Sand rollen zum Horizont wie ein erstarrter Ozean. Die Sonne brennt ohne Gnade, und der Wind formt das Land Stunde um Stunde um.',
    'Eine weite, steinige Wüste aus schwarzem Basalt und orangem Sand. Die Hitze strahlt in sichtbaren Wellen vom Boden, und Stille herrscht.',
    'Die Wüste ist merkmallos und tödlich. Eure Wasserschläuche fühlen sich mit jedem Schritt leichter an. Eine Reihe ferner Palmen könnte real sein — oder nicht.',
    'Sand, soweit das Auge reicht. Die Stille ist so vollkommen, dass ihr euer eigenes Blut rauschen hört.',
    'Ein halb vergrabenes Skelett ragt aus einer Düne — menschlich oder nicht, das ist schwer zu sagen. Die Wüste bewahrt ihre Geheimnisse.',
  ],
  arid_arctic: [
    'Nachts wird die Wüste kalt — bitter, tödlich kalt. Frost stäubt den Sand bei Morgengrauen, bevor die Sonne ihn innerhalb einer Stunde verbrennt.',
    'Eine Höhenwüste, in der eisige Winde eine Landschaft aus steinigem Geröll durchfegen. Sie ist gleichzeitig ausgedörrt und gefroren.',
    'Der Temperaturunterschied zwischen Tag und Nacht ist mörderisch. Felsen platzen vom ständigen Wechsel zwischen Hitze und Frost.',
    'Eis bildet sich in den Schatten der Felsen, nur um mittags wieder zu verdampfen. Dieses Land kann sich nicht entscheiden, ob es brennen oder frieren will.',
    'Die Sterne in der eisigen Wüstennacht sind so zahlreich und klar, dass der Himmel selbst zu leuchten scheint.',
  ],
  arid_coastal: [
    'Ein trostloses, windgepeitschtes Ufer, wo Wüste auf Ozean trifft. Gebleichtes Treibholz und Muscheln säumen einen Strand aus grobem, gelbem Sand.',
    'Die Küste ist eine flache Weite aus Salzwiesen und Wattflächen, von der Sonne hartgebacken. Flamingos waten in den flachen Lagunen.',
    'Salzverkrustete Felsen ragen aus dem Sand am Ufer. Die Brandung klingt gedämpft, als wäre selbst das Meer von der Hitze erschöpft.',
    'Ein verlassener Fischerhafen verrottet am Strand. Die Boote sind vertrocknet und rissig, und Salzkristalle überkrusten die leeren Netze.',
    'Der Wind trägt den Geruch von Salz und heißem Sand. Am Horizont verschwimmt die Grenze zwischen Meer und Wüste zu einer einzigen flimmernden Linie.',
  ],
  arid_jungle: [
    'Eine ummauerte Oase voller Dattelpalmen und dichtem Grün — ein schockierender Kontrast zur kahlen Ödnis ringsum. Eine Quelle sprudelt in ihrem Zentrum.',
    'Um diese Oase drängt sich dichte Vegetation an den Ufern eines schrumpfenden Teiches. Der Zusammenprall von üppigem Grün und versengtem Sand ist frappierend.',
    'Papageien und bunte Finken bevölkern die Palmen der Oase. Es fühlt sich an wie ein Splitter des Paradieses, verloren im Meer der Wüste.',
    'Das Wasser der Quelle ist kühl und süß — ein Geschenk nach Tagen in der Dürre. Doch die Spuren am Ufer zeigen, dass ihr nicht die Einzigen seid, die es suchen.',
    'Üppige Farne und Kletterpflanzen bedecken die Felswände der Oase. Schmetterlinge flattern durch das schattige Grün wie lebende Edelsteine.',
  ],
  arid_underdark: [
    'Ein Höhlenmund gähnt in der Canyonwand und haucht kühle, feuchte Luft — kostbare Erleichterung von der Wüstenhitze. Uralte Gravuren flankieren den Eingang.',
    'Ein Erdloch im Hartboden enthüllt ein Höhlensystem darunter. Die Temperatur fällt dramatisch, je tiefer ihr hinabsteigt.',
    'Im Inneren der Höhle tropft Wasser von der Decke — ein unfassbarer Luxus in dieser Wüste. Krüge und Schalen zeigen, dass andere diesen Ort schon nutzten.',
    'Die Wände glänzen feucht, und der Geruch von feuchtem Stein verdrängt den allgegenwärtigen Staub. Fledermäuse flattern erschrocken auf, als ihr eintretet.',
    'Der Gang wird enger, dann weitet er sich zu einer Halle mit einem unterirdischen See. Das Wasser ist still und schwarz — und unergründlich tief.',
  ],
  arid_water: [
    'Ein verborgener Oasensee, unwahrscheinlich blau vor dem sandfarbenen Wüstenhintergrund. Palmen säumen sein Ufer, und das Wasser ist klar und süß.',
    'Ein schlammiger, schrumpfender Fluss gräbt sich einen Kanal durch die Wüste. Seine Ufer sind von Salzablagerungen und verzweifelter Vegetation gesäumt.',
    'Das Wasser ist überraschend warm. Dampf steigt in der Morgenkühle auf und verwandelt den See in ein unwirkliches Dampfbad.',
    'Tiere versammeln sich an der Wasserstelle — Gazellen, Vögel, Eidechsen. Für einen Moment herrscht Frieden zwischen Jäger und Beute.',
    'Der See ist flach und seine Ränder von getrockneten Algen gesäumt. Er war einmal größer — die Wasserlinie ist deutlich an den Felsen abzulesen.',
  ],
  arid_road: [
    'Ein Karawanenpfad, markiert von Steinpyramiden. Der Sand hat ihn stellenweise überweht, und alte Wagenspuren sind der einzige Wegweiser.',
    'Die Handelsstraße ist ein gebrannter Lehmstreifen durch die Ödnis. Gebleichte Tierschädel markieren die Route in Abständen — grimmige Meilensteine.',
    'Kamelspuren und Fußabdrücke in verschiedenen Stadien der Verwitterung zeigen, dass dieser Pfad noch genutzt wird — wenn auch selten.',
    'Am Wegesrand steht ein halb versandeter Brunnen. Ob er noch Wasser führt? Die verwitterte Aufschrift verspricht „Drei Tage bis zur nächsten Karawanserei".',
    'Die Straße führt schnurgerade zum Horizont. In dieser endlosen Weite wirkt jeder Schritt sinnlos — doch aufzugeben wäre tödlich.',
  ],

  // ━━━ VULKANISCH (VOLCANIC) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  volcanic_plains: [
    'Eine flache Weite aus gehärtetem Lavastein, rissig und tückisch. Dampfwolken steigen aus Spalten, und die Luft stinkt nach Schwefel.',
    'Aschebedeckte Ebenen erstrecken sich in alle Richtungen, grau und leblos. Der Boden ist warm unter den Füßen, und leichte Beben sind ein ständiger Begleiter.',
    'Der Boden ist schwarz und glasig — frische Lava, erst vor wenigen Jahren erstarrt. Hier und da glüht es noch orange in den Rissen.',
    'Asche knirscht unter euren Stiefeln. Vereinzelte verkohlte Baumstümpfe ragen aus dem grauen Ödland wie verbrannte Finger.',
    'Die Hitze steigt von unten. Selbst durch die Sohlen eurer Stiefel spürt ihr die vulkanische Wärme, die im Gestein schlummert.',
  ],
  volcanic_forest: [
    'Verkohlte Baumstämme stehen wie geschwärzte Säulen in einem von pyroklastischem Strom getöteten Wald. Neues Wachstum — Farne und Schösslinge — drückt durch die Asche.',
    'Der Wald wächst auf alten Lavaströmen; Bäume bohren ihre Wurzeln in Risse im Basalt. Der Boden ist reich und dunkel, aber die Luft trägt einen beißenden Geschmack.',
    'Zwischen verkohlten Stämmen und frischem Grün entsteht ein seltsamer Kontrast. Die Natur erobert zurück, was das Feuer genommen hat.',
    'Dampf entweicht dem Boden zwischen den Bäumen, und Farne wachsen in überdimensionaler Größe — genährt von den vulkanischen Mineralien.',
    'Ein Rabe sitzt auf einem schwarzen Ast und beobachtet euch. Der Wald riecht nach Schwefel und neuem Leben zugleich.',
  ],
  volcanic_hills: [
    'Schlackenkegel und Lavagrate erheben sich aus dem aschenen Gelände. Öffnungen zischen mit entweichendem Gas, und der Fels ist warm unter den Füßen.',
    'Der Hügel ist ein Flickwerk alter Lavaströme — manche glänzend schwarzer Obsidian, andere rau und rostfarben von oxidiertem Eisen.',
    'Die Luft flimmert von aufsteigendem Dampf. Gelbe Schwefelkristalle umkrusten die Ränder der Dampföffnungen wie giftige Juwelen.',
    'Ein Krater öffnet sich vor euch — ein perfekter Kessel, in dem ein See aus trübem, schwefelgelbem Wasser dampft.',
    'Die Lavahügel sind zerklüftet und schroff. Jeder Fehltritt könnte euch in eine verborgene Spalte stürzen, aus der heißer Dampf emporzischt.',
  ],
  volcanic_mountains: [
    'Der Vulkan ragt drohend über euch auf, sein Gipfel in Rauch gehüllt und vom gelegentlichen Aufblitzen orangeroten Lichts erhellt. Lavaströme narben die oberen Hänge.',
    'Ein Berg aus schwarzem Basalt und grauer Asche, seine Flanken von tiefen Rinnen zerschnitten. Heiße Quellen sammeln sich in den niedrigen Tälern und dampfen in der kühlen Morgenluft.',
    'Der Gipfel grummelt leise — eine Warnung oder ein Versprechen. Rauchsäulen steigen auf und verdunkeln zeitweise die Sonne.',
    'Erstarrte Lavaströme haben bizarre Formen geschaffen — Brücken, Tunnel, Türme aus schwarzem Glas. Eine Landschaft wie von einer anderen Welt.',
    'Der Schwefelgeruch wird mit jedem Höhenmeter stärker. Oben, wo der Kraterrand beginnt, glüht es orangerot in der Tiefe.',
  ],
  volcanic_swamp: [
    'Ein geothermaler Sumpf aus heißen Schlammtümpeln und dampfenden Öffnungen. Das Wasser ist beunruhigend warm, und Gasblasen platzen an der Oberfläche mit einem schwefligen Plopp.',
    'Saure heiße Quellen speisen ein giftiges Feuchtgebiet. Die Vegetation hier ist seltsam — blass, schwammig und gedeihend auf Mineralien, die normale Pflanzen töten würden.',
    'Blubbernde Schlammtöpfe und zischende Fumarolen machen diesen Sumpf zu einem Ort, der mehr nach Hölle als nach Wildnis aussieht.',
    'Das Wasser wechselt die Farbe — milchweiß, schwefelgelb, rostrot. Jeder Tümpel hat seine eigene giftige Chemie.',
    'Bizarre, bleiche Pflanzen mit fleischigen Blättern haben sich an diese lebensfeindliche Umgebung angepasst. Sie sehen aus, als kämen sie von einem anderen Stern.',
  ],
  volcanic_desert: [
    'Ein kahles Lavafeld erstreckt sich vor euch — eine Höllenlandschaft aus gezacktem schwarzem Gestein und glühenden Spalten. Die Hitze ist erdrückend, selbst ohne Sonne.',
    'Der Infernofluss — ein langsam fließender Kanal aus geschmolzenem Gestein — durchschneidet dieses verwüstete Ödland. Die Luft flimmert, und der Boden zischt bei jedem Schritt.',
    'Obsidiansplitter liegen verstreut wie schwarzes Glas. Ein falscher Schritt, und die rasiermesserscharfen Kanten schneiden durch Stiefel und Haut.',
    'Die Glut unter der Oberfläche lässt den Boden in der Dunkelheit schwach leuchten — ein unheimliches, orangerotes Adernetz unter schwarzem Stein.',
    'Nichts lebt hier. Selbst die Luft scheint verbrannt. Dies ist ein Ort des Feuers, nicht der Sterblichen.',
  ],
  volcanic_arctic: [
    'Ein unmögliches Aufeinandertreffen von Feuer und Eis. Gletscher kalben in dampfende Seen, und Säulen aus Wasserdampf steigen dort auf, wo Lava auf gefrorenen Boden trifft.',
    'Geothermale Öffnungen haben Kanäle durch das Eis geschmolzen und warme Oasen geschaffen, umgeben von gefrorener Tundra. Die Mischung ist desorientierend.',
    'Eisblöcke und Dampfsäulen stehen nebeneinander in surrealer Harmonie. Wo das heiße Wasser den Schnee berührt, entstehen Regenbogen aus Gischtpartikeln.',
    'Der Kontrast ist verstörend: eine Hand im warmen Quellwasser, die andere erfriert in der arktischen Luft. Zwei Welten, die nicht zusammenpassen.',
    'Zwischen den Eisflächen dampfen grüne Moospolster, genährt von der Erdwärme. Kleine rote Käfer krabbeln unbeirrt über den Schneerand.',
  ],
  volcanic_coastal: [
    'Schwarze Sandstrände aus zermahlenem Vulkanglas erstrecken sich die Küste entlang. Das Wasser dampft, wo heiße Quellen in den kalten Ozean fließen.',
    'Hexagonale Basaltsäulen, fremd und beeindruckend, ragen aus der Brandung. Geysire brechen periodisch entlang der Küstenlinie aus und schleudern Fontänen kochenden Wassers empor.',
    'Der Sand unter euren Füßen ist tiefschwarz und überraschend warm. Dampf steigt aus dem Meerwasser, wo es auf die erhitzten Steine trifft.',
    'Eine Steilküste aus erstarrter Lava fällt ins Meer ab. Die Wellen nagen geduldig an dem Gestein und formen Höhlen und Bögen.',
    'Seevögel nisten auf den warmen Felsen der Küste. Das Zusammenspiel von Feuer, Stein und Meer ist schaurig schön.',
  ],
  volcanic_jungle: [
    'Üppiges tropisches Wachstum hat die alten Lavafelder besiedelt. Der Boden hier ist unglaublich fruchtbar — Pflanzen wachsen zu enormer Größe, genährt von vulkanischen Mineralien.',
    'Ein dampfender Dschungel füllt eine Vulkankaldera, gespeist von heißen Quellen und Erdwärme. Die Vegetation wirkt prähistorisch in ihrer Gewaltigkeit.',
    'Riesige Baumfarne und Schachtelhalme erinnern an das Zeitalter der Dinosaurier. Die Luft ist schwer, feucht und riecht nach Schwefel und Blüten.',
    'Überall dampft es. Orchideen in unglaublichen Farben wachsen auf den warmen Felsen, und Eidechsen so groß wie Katzen sonnen sich auf den Lavasteinen.',
    'Die Kaldera ist ein vergessenes Paradies — oder ein Gefängnis. Die steilen Wände lassen sich nur an wenigen Stellen erklimmen.',
  ],
  volcanic_underdark: [
    'Die Kaverne glüht im Licht eines Magmaflusses tief unten. Die Hitze ist brutal, und die Steinwände sind warm unter den Fingern.',
    'Lavatunnel winden sich durch das vulkanische Gestein, ihre Wände von uralten Strömen glattgeschliffen. Die Luft ist heiß, metallisch und kaum atembar.',
    'Der Schein des flüssigen Gesteins wirft tanzende Schatten an die Wände. Die Hitze ist so intensiv, dass Metall zu glühen beginnt.',
    'Obsidiansäulen stützen einen natürlichen Gewölbebogen. Darunter fließt ein Bach aus geschmolzenem Gestein, langsam und leuchtend wie flüssiges Gold.',
    'Die Luft ist so dünn und heiß, dass jeder Atemzug in der Kehle brennt. Mineralkristalle wachsen aus den Wänden in unwirklichen Formen.',
  ],
  volcanic_water: [
    'Ein kochender See füllt einen Vulkankrater, seine Oberfläche aufgewühlt von Gas und Dampf. Das Wasser ist sauer — nichts lebt in seinen smaragdgrünen Tiefen.',
    'Heiße Quellen kaskadieren über terrassierte Becken aus weißen Mineralablagerungen. Das Wasser reicht von verbrühend heiß bis angenehm warm in den unteren Bassins.',
    'Dampf steigt vom See auf wie der Atem eines schlafenden Drachen. Die Farbe wechselt je nach Mineralgehalt von Milchblau zu Schwefelgelb.',
    'Sinterterrassen glänzen in sanftem Perlmutt. Das warme Wasser hat über Jahrhunderte diese natürlichen Kunstwerke geschaffen.',
    'Am Rand des heißen Sees liegen verkalkte Skelette von Tieren, die zu nah ans Wasser kamen. Die Warnung ist deutlich.',
  ],
  volcanic_road: [
    'Ein Pfad aus erkalteter Lava, glattgelaufen von Reisenden. Er windet sich zwischen dampfenden Öffnungen und Obsidianklippen. Metallteile von Wagen sind zu roten Flocken korrodiert.',
    'Der Ascheweg — eine aufgeschüttete Straße aus festgestampftem Vulkankies — überquert die Lavafelder. Schwefelgelbe Ablagerungen markieren die Ränder der Route.',
    'Der Weg ist schwarz und glänzend, als wäre er frisch geteert. Doch es ist erstarrte Lava, die bei jedem Schritt hohl klingt.',
    'Steinerne Wegmarkierungen aus Basalt trotzen dem Verfall. Die Schriftzeichen darauf sind in einer Sprache verfasst, die niemand mehr spricht.',
    'Die Straße führt direkt auf den rauchenden Berg zu. Mit jedem Schritt wird es wärmer, und der Schwefelgeruch beißt in den Augen.',
  ],

  // ━━━ MARITIM (MARITIME) ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━

  maritime_plains: [
    'Salzhaltige Winde fegen über niedrige Küstenwiesen. Das Gras ist dicht und grob, permanent landwärts gebogen vom vorherrschenden Seewind.',
    'Flaches, sumpfiges Ackerland erstreckt sich vom Ufer landeinwärts. Entwässerungsgräben glitzern im grauen Licht, und die Rufe der Seevögel sind allgegenwärtig.',
    'Die Wiese ist durchzogen von Prielen, die bei Flut volllaufen. Wattwürmer hinterlassen kleine Häufchen im salzigen Schlick.',
    'Schafe grasen auf dem Deich, ihre Wolle feucht vom Sprühnebel. Der Horizont verschwimmt zwischen Himmel und Meer zu einer endlosen Graufläche.',
    'Der Wind schmeckt nach Salz und Algen. Möwen kämpfen am Himmel um einen Fisch, und das ferne Tuten eines Nebelhorns dringt über die Ebene.',
  ],
  maritime_forest: [
    'Ein nebelverhangener Wald aus verdrehten, windgestutzten Bäumen, behangen mit Bartflechten. Die Luft ist feucht, und alles glänzt vor Nässe.',
    'Dichtes Küstenwaldland presst sich an die Seeklippen. Die Salzluft hat die Bäume auf der Windseite zu knorrigen, bonsaiartigen Formen gestutzt.',
    'Nebel wabert zwischen den Stämmen wie eine lebende Kreatur. Jeder Schritt auf dem feuchten Laub wird vom entfernten Grollen der Brandung begleitet.',
    'Moose und Farne bedecken jeden Stamm und jeden Stein. Die Luft ist so feucht, dass Tropfen von den Blättern fallen, obwohl es nicht regnet.',
    'Der Wald riecht nach Salz, Erde und Harz. Zwischen den Bäumen blitzt das Meer hervor — grau und endlos.',
  ],
  maritime_hills: [
    'Seeklippen steigen steil aus der krachenden Brandung auf, ihre grasigen Kuppen vom ewigen Wind gepeitscht. Nistende Seevögel bevölkern jede Felsnische.',
    'Sanft geschwungene Küstenhügel, ihre Seeseiten kahl und windgepeitscht, ihre Landseiten geschützt und grün. Nebel sammelt sich in jeder Senke.',
    'Vom Hügelkamm aus seht ihr die ganze Küstenlinie — zerklüftete Klippen, verborgene Buchten und die weiße Linie der Brandung.',
    'Windgebeugte Hecken und Steinmauern durchziehen die Hügel. Ein einsamer Leuchtturm steht auf dem höchsten Punkt und blinkt ins Grau.',
    'Sturmvögel segeln auf den Aufwinden der Klippen. Ihre Schreie mischen sich mit dem Donnern der Wellen weit unten.',
  ],
  maritime_mountains: [
    'Felstürme und Küstengipfel tauchen aus dem Nebel auf wie die Rückenplatten eines gewaltigen Wesens. Wasserfälle stürzen direkt ins Meer.',
    'Die Fjordwände steigen senkrecht auf beiden Seiten empor, ihr graues Gestein durchzogen von Kaskaden. Der Durchlass ist eng, dunkel und kalt.',
    'Das Meer hat Höhlen in die Bergflanken gegraben, deren Eingänge bei Flut verschwinden. Das Echo der Wellen klingt wie fernes Trommeln.',
    'Schneebedeckte Gipfel spiegeln sich im stillen Fjord. Die Luft ist klar und riecht nach Kiefern und Salzwasser.',
    'Ein Seeadler kreist über dem Fjord, sein Schrei hallt zwischen den steilen Felswänden wider. Die Landschaft ist gewaltig und ehrfurchtgebietend.',
  ],
  maritime_swamp: [
    'Ein Gezeitensalzmoor, durchkreuzt von schlammigen Kanälen, die mit der Flut an- und abschwellen. Watvögel staksen durch das Schilf.',
    'Brackige Feuchtgebiete, wo Süßwasserbäche auf das Meer treffen. Der Schlamm ist tief, der Halt tückisch, und der Geruch von Verwesung ist stark.',
    'Bei Ebbe offenbart das Watt seine Geheimnisse — Muschelbänke, Krebse und die Spuren eines Reihers, der hier vor Stunden jagte.',
    'Der Schlick schmatzt bei jedem Schritt. Salzkraut und Queller wachsen in seltsamen Mustern, und der Geruch von Jod hängt in der feuchten Luft.',
    'Ein Priel schlängelt sich durch die Marsch. Bei auflaufendem Wasser wird er in Minuten vom harmlosen Rinnsal zum reißenden Strom.',
  ],
  maritime_desert: [
    'Eine Nebelwüste, in der Dunst vom Ozean hereinrollt, aber kein Regen fällt. Feuchtigkeit kondensiert auf jeder Oberfläche, doch der Boden bleibt ausgedörrt.',
    'Eine kahle, salzkrustige Fläche nahe der Küste. Sturmfluten haben jede Vegetation getötet und eine trostlose weiße Ebene hinterlassen.',
    'Seltsame Pflanzen fangen den Nebel mit ihren Blättern ein — das ist ihre einzige Wasserquelle in dieser paradoxen Wüste am Meer.',
    'Der Nebel ist so dicht, dass ihr keine zehn Schritt weit sehen könnt. Die Brandung donnert irgendwo nahe, aber die Richtung ist nicht auszumachen.',
    'Salzstaub wirbelt über die Ebene und brennt in den Augen. Das Meer ist nah, doch sein Wasser ist nutzlos für den Durst.',
  ],
  maritime_arctic: [
    'Eine gefrorene Küstenlinie, gepeitscht von eisigen Ozeanstürmen. Sprühwasser gefriert augenblicklich auf jeder Oberfläche und schafft bizarre Eisformationen.',
    'Das Nordufer ist eine Wand aus Eis, die auf dunkles, aufgewühltes Wasser trifft. Eisberge kalben und gleiten mit donnerndem Krachen ins Meer.',
    'Eiszapfen so lang wie Lanzen schmücken die Klippenkante. Darunter peitschen schwarze Wellen gegen den gefrorenen Fels.',
    'Sturmböen treiben Eisnadeln horizontal durch die Luft. Jede Sekunde im Freien bringt Erfrierungen näher.',
    'Robben haben sich auf einer Eisscholle zusammengerollt, unbeeindruckt von der Kälte, die euch bis auf die Knochen durchdringt.',
  ],
  maritime_coastal: [
    'Eine klassische Küstenlandschaft — Sandstrände, versteckte Buchten, Gezeitenhöhlen und der immerwährende Rhythmus der Wellen. Salz liegt in allem.',
    'Ein betriebsamer Hafenküstenstreifen aus Kais, Stegen und Fischerbooten. Der Geruch von Teer, Salzfisch und Tau hängt schwer in der Luft.',
    'Meereshöhlen durchlöchern die erodierten Kalksteinklippen. Bei Ebbe winken dunkle Gänge; bei Flut verschluckt das Meer sie ganz.',
    'Bunte Fischerboote liegen auf dem Kiesstrand, ihre Netze zum Trocknen aufgespannt. Kinder spielen zwischen den Hummerfallen.',
    'Die Klippe fällt dreißig Meter senkrecht ins Meer. Unten schäumt die Brandung weiß, und Kormorane trocknen ihre Flügel auf den nassen Felsen.',
  ],
  maritime_jungle: [
    'Ein regendurchweichter Küstendschungel, wo Seenebel und tropische Feuchtigkeit sich vereinen. Alles tropft; alles ist grün; alles lebt.',
    'Dichter Mangrovenwald am Flussdelta — ein Labyrinth aus Wurzeln, Wasserläufen und Schlickflächen. Navigation ist nur auf dem Wasser möglich.',
    'Der Dschungel reicht bis ans Wasser. Salzwasserkrokodile gleiten lautlos zwischen den Mangrovenwurzeln, und der Geruch nach Fäulnis und Blüten vermischt sich.',
    'Epiphyten bedecken jeden Ast, und Nebel hängt zwischen den Stämmen. Das Meer ist nur wenige Schritte entfernt, doch im Dickicht scheint es eine andere Welt.',
    'Krabben krabbeln über freiliegende Wurzeln, und bunte Papageien schreien aus den Kronen. Der Boden ist nirgends fest — nur Schlamm, Wurzeln und Wasser.',
  ],
  maritime_underdark: [
    'Ein Meereshöhlensystem, geschnitzt von Jahrtausenden der Gezeitenwirkung. Die Gänge fluten und entleeren sich mit der Tide — das Timing eures Abstiegs ist entscheidend.',
    'Die Felswand ist von Tunneln durchsetzt. Das Brausen des Ozeans hallt durch sie hindurch und erzeugt einen unheimlichen, rhythmischen Puls.',
    'Bei Ebbe offenbaren sich Gänge, die normalerweise unter Wasser liegen. Seeanemonen, Seesterne und Muscheln bedecken die Wände in salzigen Farben.',
    'Das Wasser schießt rhythmisch durch die Höhle wie der Atem eines Riesen. Bei Flut wird der Rückzug abgeschnitten — ihr müsst die Zeit im Blick behalten.',
    'Phosphoreszierende Algen malen die feuchten Wände in bläuliches Licht. Das Geräusch der Brandung dringt gedämpft durch den Fels wie ein fernes Herzschlagen.',
  ],
  maritime_water: [
    'Offenes Meer erstreckt sich in alle Richtungen — graugrüne Dünung unter bleigrauem Himmel. Der Wind ist stark und trägt den Geschmack von Salz.',
    'Eine geschützte Bucht mit dunklem Wasser, umringt von steilen, bewaldeten Ufern. Fischerboote schaukeln sanft an ihren Moorings.',
    'Die See ist rau heute. Wellenkämme brechen sich weiß, und der Wind pfeift durch die Takelage eines fernen Schiffes.',
    'Delfine springen in der Ferne, ihre Silhouetten blitzen silbern gegen das graue Meer. Ein gutes Zeichen — oder auch nicht.',
    'Nebelbänke ziehen über das Wasser und verschlucken den Horizont. Das einzige Geräusch ist das Plätschern der Wellen gegen den Bug.',
  ],
  maritime_road: [
    'Eine Küstenstraße, in die Felswand gemeißelt, ihr Meeresrand abbröckelnd. Sprühwasser der Wellen unter euch überzieht die Steine mit glitschigem Salz.',
    'Die alte Hafenstraße folgt der Küstenlinie, vorbei an Fischerdörfern und zwischen Trockenständern schwer beladen mit Salzfisch.',
    'Der Weg ist rutschig von Algen und Salzwasser. Ein falscher Schritt, und ihr rutscht die Klippe hinab ins tosende Meer.',
    'Steinerne Poller und verrostete Ketten säumen die Straße — Überreste alter Häfen, deren Dörfer längst verlassen sind.',
    'Der Wind ist hier so stark, dass ihr euch dagegen lehnen müsst. Salzgischt peitscht euch ins Gesicht, und das Donnern der Brandung übertönt jedes Gespräch.',
  ],
};
